### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by paulocoutinhox** [ezored/ezored#20]
Mac Catalyst Support

1. Support Mac Catalyst deployment on iOS sample project. ✅ 
2. Change iOS framework creation to support group of framework (ios, ios_simulator, ios_catalyst). ✅ 
3. Create new ios_framework target verb to generate xcframework (python make.py target ios_framework package_xcframework). It need follow the steps: conan, build, package, package_xcframework. ✅ 
4. Fix travis to test Linux, macOS and iOS. ✅ 
5. Add FileHelper implementation for desktop app. ✅ 
6. Generate distribution file with prebuilt binaries. ✅ 

If you want test catalyst now:

1. Clone project and go to branch "xcframework-support".
2. Download prebuilt files: `python make.py dist download`.
3. Execute: `open projects/ios/Sample/Sample.xcodeproj/`.
4. Select target "Sample > My Mac".
5. Try run. You may need check certificates. But you can put on automatic for your account.

**Comment by paulocoutinhox** [comment]
Report:

All items are done! ✅

**Comment by paulocoutinhox** [comment]
SQLite 3 problems:

Description: SQLite 3 is the only library now that don't work with Mac Catalyst. There is a check about use or not function "gethostuuid". With current checks cannot be able desactive this function call. The correct patch is change on line 32610 the checks to:

```
#if defined(__APPLE__) && ((__MAC_OS_X_VERSION_MIN_REQUIRED > 1050) || \
                           (__IPHONE_OS_VERSION_MIN_REQUIRED > 2000))
#  if (!defined(TARGET_OS_EMBEDDED) || (TARGET_OS_EMBEDDED==0)) \
       && (!defined(TARGET_IPHONE_SIMULATOR) || (TARGET_IPHONE_SIMULATOR==0)) \
       && (!defined(TARGET_OS_MACCATALYST) || (TARGET_OS_MACCATALYST==0))
#    define HAVE_GETHOSTUUID 1
#  else
#    warning "gethostuuid() is disabled."
#  endif
#endif
```

With this the compilation go nice.

**Comment by paulocoutinhox** [comment]
Video with Mac Catalyst running with ezored:

https://www.youtube.com/watch?v=ro2WVX_wHuQ

**Comment by paulocoutinhox** [comment]
Created a patch to conan sqlite3 dependency:
https://github.com/conan-io/conan-center-index/pull/530

It will let us compile and disable the function "gethostuuid" for Mac Catalyst.

**Comment by paulocoutinhox** [comment]
**XCode 11 - Code Sign Error On XCFramework For MAC**

I made a video showing:

https://www.youtube.com/watch?v=3hbXCVv5B2I&feature=youtu.be​

**Description:**

XCode 11 - Code Sign Error On XCFramework For MAC Description of problems:

1 - I have a working framework and xcframework from my project ezored (https://github.com/ezored/ezored). It can be downloaded here: http://public.ezored.com/ezored/prebuilt/dist.zip

2 - Im compiling my sample application for iPhone / Simulator and it is working fine

3 - I tried build for Mac Catalyst and get codesign error. I already tried a lot of things from web, but without success

4 - Error: /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-cxozqcnzzwknfygqkfaxomntiilp/Build/Products/Debug-maccatalyst/Sample.app: code object is not signed at all In subcomponent: /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-cxozqcnzzwknfygqkfaxomntiilp/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/Ezored.framework Command CodeSign failed with a nonzero exit code

Can anyone help me?

**Comment by paulocoutinhox** [comment]
All problems are solved from ezored site and conan.

The only problem now is with xcode generator from **cmake** that don't recognize something releated to arch and don't generate frameworks direct from xcode for desired arch.

Issue on cmake:
https://gitlab.kitware.com/cmake/cmake/-/issues/20246

**Comment by paulocoutinhox** [comment]
Hi,

Im with a problem when sign Mac Catalyst xcframework. 

Can be downloaded here:
https://ezored.s3.amazonaws.com/dist/ios_framework/1.0.0/dist.tar.gz

Error:
```
dyld: Library not loaded: @loader_path/Frameworks/ezored.framework/Versions/A/ezored
  Referenced from: /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/MacOS/Sample
  Reason: no suitable image found.  Did find:
	/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/ezored.framework/ezored: code signature in (/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/ezored.framework/ezored) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/ezored.framework/Versions/A/ezored: code signature in (/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/ezored.framework/Versions/A/ezored) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
(lldb) 
```

![image](https://user-images.githubusercontent.com/395096/109378832-72c6a700-78b4-11eb-93b6-5900edd066ea.png)

Can anyone help me?

**Comment by paulocoutinhox** [comment]
The problem is related to sign:

COMPLETE:

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Intermediates.noindex/Sample.build/Debug-maccatalyst/Sample.build/Script-B22567A9E6E019254B753C75.sh (in target 'Sample' from project 'Sample')
    cd /Users/paulo/Developer/workspaces/cpp/ezored/projects/ios/Sample
    /bin/sh -c /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Intermediates.noindex/Sample.build/Debug-maccatalyst/Sample.build/Script-B22567A9E6E019254B753C75.sh

mkdir -p /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/XCFrameworkIntermediates/ezored/ezored.framework" "/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks"
building file list ... done

sent 288 bytes  received 20 bytes  616.00 bytes/sec
total size is 8606015  speedup is 27941.61
Code Signing /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework with Identity Apple Development: Paulo Coutinho (Z65H7K3Q57)
/usr/bin/codesign --force --sign 7E004155F30DD932289572ED582FE16F89C0412F  --preserve-metadata=identifier,entitlements '/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework'
/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework: bundle format is ambiguous (could be app or framework)
Command PhaseScriptExecution failed with a nonzero exit code
```

SEPARATED:

```
Showing Recent Messages
Code Signing /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework with Identity Apple Development: Paulo Coutinho (Z65H7K3Q57)
```

```
Showing Recent Messages
/usr/bin/codesign --force --sign 7E004155F30DD932289572ED582FE16F89C0412F  --preserve-metadata=identifier,entitlements '/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework'
```

```
Showing Recent Messages
/Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework: bundle format is ambiguous (could be app or framework)
```

I execute it manually and have the same problem (mac catalyst):

```
/usr/bin/codesign --force --sign 7E004155F30DD932289572ED582FE16F89C0412F  --preserve-metadata=identifier,entitlements Pods/ezored/Release/ezored.xcframework/ios-x86_64-maccatalyst/ezored.framework 
Pods/ezored/Release/ezored.xcframework/ios-x86_64-maccatalyst/ezored.framework: bundle format is ambiguous (could be app or framework)
```

And for iOS it works:

```
/usr/bin/codesign --force --sign 7E004155F30DD932289572ED582FE16F89C0412F  --preserve-metadata=identifier,entitlements Pods/ezored/Release/ezored.xcframework/ios-arm64_arm64e_armv7_armv7s/ezored.framework 
```

The problem is related to signing a framework for Mac Catalyst. Download the xcframework here to test:
https://ezored.s3.amazonaws.com/dist/ios_framework/1.0.0/dist.tar.gz

Can anyone help me?

**Comment by giona69** [comment]
anyone solved this? I have the same problem (on y framework distributed as cocoapod) during the archive / upload step

**Comment by paulocoutinhox** [comment]
Hi,

I solved one problem, now it is working when compile (sign process).

The only problem now is when execute, because the library is not found (but is there):

```
dyld: Library not loaded: @loader_path/Frameworks/ezored.framework/Versions/A/ezored
  Referenced from: /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/MacOS/Sample
  Reason: image not found
(lldb) 
```

See:

```
 ls -lh /Users/paulo/Library/Developer/Xcode/DerivedData/Sample-abxdtyhuvlqxbfhcnvbmzhxhtwjl/Build/Products/Debug-maccatalyst/Sample.app/Contents/Frameworks/ezored.framework
total 0
lrwxr-xr-x  1 paulo  staff    26B Aug 13 14:28 Resources@ -> Versions/Current/Resources
drwxr-xr-x  4 paulo  staff   128B Aug 13 14:28 Versions/
lrwxr-xr-x  1 paulo  staff    23B Aug 13 14:28 ezored@ -> Versions/Current/ezored
```

To make it work, you need use for now branch "version-3" that is a working in progress version of architecture.

**Comment by paulocoutinhox** [comment]
Hi @giona69,

I solved all problems. It is on branch "version-3" of architecture.

<img width="901" alt="Screen Shot 2021-08-30 at 19 21 40" src="https://user-images.githubusercontent.com/395096/131414426-ffd24c16-c890-423b-b67e-4c03c6f7aa17.png">
