### ISSUE TITLE
iOS build on Big Sur 11.3.1 fails

### ISSUE THREAD

**Issue by nschlehe** [ezored/ezored#29]
After following the "How to start" guide on macOS for iOS the build fails on sqlite with the following error:

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.21/Modules/Platform/iOS-Initialize.cmake:4 (message):
  
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
  is not an iOS SDK
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.21/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:2 (project)
````

The other packages build just fine when I comment out sqlite: 

```
    def requirements(self):
        # self.requires("sqlite3/3.35.5")
        self.requires("rapidjson/1.1.0")
        self.requires("openssl/1.1.1k")
        # self.requires("sqlitecpp/2.5.0")
        self.requires("date/3.0.1")
```

Nice project, thanks!

**Comment by paulocoutinhox** [comment]
Hi,

Maybe can be related to CMake 3.21.

But check if you have selected correctly the command line tools:

![image](https://user-images.githubusercontent.com/395096/123322139-48a38f80-d50a-11eb-97c9-9393e5fc0c15.png)

If it is OK, try install cmake 3.20 instead of 3.21.

Post here your results to i help you.

**Comment by nschlehe** [comment]
I tried first with 3.20 with the same problem. Then I installed 3.21 without success.
Locations dialog looks exactly like mine.
Interestingly it only fails on sqlite the other libs get cross compiled.

**Comment by paulocoutinhox** [comment]
Hi,

I will try help you with these steps.

[1] Do you execute this command?

```
python make.py conan setup 
```

[2] Do you have changed something in `files/config/target_ios.py`? 

Your problem is that iOS SDK is pointed to macOS SDK:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
  is not an iOS SDK
```

Post here your changes, if have.

[3] Try update your installed conan library:
```
pip install conan --upgrade
```

[4] If you changed some other files, please post here to i try help you.

After check all this, post here the results.

Thanks.

**Comment by nschlehe** [comment]
Thanks for your suggestions, but it didn't resolve the issue.
I started debugging the issue today and found out that `CMAKE_OSX_SYSROOT` is not properly resolved in
`Platform/Darwin-Initialize.cmake`

It is set based on `$ENV{SDKROOT}` which is somehow set to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`
but i couldn't find out where it's set. In my shell env it's not.
Anyways, when I set it to the iPhone SDK it works:

`export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk`

Thanks for your support.

**Comment by nschlehe** [comment]
Follow up:
After playing around with other dependencies I had again build errors so I investigated further.
Somehow my python3 sets `SDKROOT` and overriding it from the outside shell breaks other packages.
My solution to the problem is to add
```python

if "SDKROOT" in os.environ:
    del os.environ["SDKROOT"]
```
in the head of make.py

Just in case someone else stumbles over this

**Comment by paulocoutinhox** [comment]
Hi,

You can check if on terminal there is an environment variable calling:

```
echo $SDKROOT
```

Because if you have, cmake will use it. See here:
https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_SYSROOT.html

```
If not set explicitly the value is initialized by the SDKROOT environment variable, if set, and otherwise computed based on the CMAKE_OSX_DEPLOYMENT_TARGET or the host platform.
```

**Comment by nschlehe** [comment]
Yes, I checked that. It's not set in the shell. Only in python, that's the weird thing
