### ISSUE TITLE
Enabling poco on target-ios fails

### ISSUE THREAD

**Issue by nschlehe** [ezored/ezored#30]
After enabling `self.requires("poco/1.10.1")` on iOS the build fails.
pcre (poco dep) builds pcregrep cli application by default and has problems with bundling. 
Adding `"pcre:build_pcregrep": False,` resolves the issue

**Comment by paulocoutinhox** [comment]
Hi,

I have opened an issue:
https://github.com/conan-io/conan-center-index/issues/6062

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

I made a pull-request to the dependency:
https://github.com/conan-io/conan-center-index/pull/6101

You don't will need your project.

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

Everything was merged. Can you test and see if it works?

Thanks.

**Comment by paulocoutinhox** [comment]
Hi @nschlehe,

I will close this issue since it was solved. If you have other problems related you can reopen or create a new issue.

Thanks.
