### ISSUE TITLE
Cannot find 'EZR*' in scope, iOS template project

### ISSUE THREAD

**Issue by ahmedkamalio** [ezored/ezored#36]
**Describe the bug**
No `EZR*` (`EZRLogger`, `EZRSharedData`, etc...) can be resolved in Swift code!

**To Reproduce**

1. Clone this repo
2. Open `projects/iOS/Sample` in terminal and do `pod install`
3. Open `projects/iOS/Sample/Sample.xcworkspace` in Xcode
4. Try to build the Sample target for any scheme

**Expected behavior**
Expected it to build without errors!

**Screenshots**
<img width="908" alt="Screen Shot 2021-12-12 at 11 09 24 PM" src="https://user-images.githubusercontent.com/35304348/145729615-423a7b2e-d69c-45c6-9c79-515e691ae57e.png">

**System (please complete the following information):**
 - OS: macOS **(m1)**
 - Version: Monterey 12.0.1 
 - Conan: 1.42.1
 - Target: iOS

**Additional context**
I'm also not able to build the Ezored library for iOS platform, it builds well for macOS but when I target iOS it throws the following error

```console
ahmed@ahmeds-mbp ezored % python3 make.py target ios prepare
[INFO] Running "prepare" on target "ios"...
[INFO] Building for: armv7/Debug...
Configuration (profile_host):
[settings]
arch=armv7
arch_build=armv8
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=iOS
os.version=9.0
os_build=Macos
[options]
ezored_arch=armv7
ezored_group=ios
ezored_name=ezored
ezored_version=1.0.0
darwin-toolchain:enable_arc=None
darwin-toolchain:enable_bitcode=True
darwin-toolchain:enable_visibility=None
[build_requires]
*: darwin-toolchain/1.3.0@ezored/stable
[env]

Configuration (profile_build):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os.version=None
os_build=Macos
[options]
[build_requires]
[env]

WARN: poco/1.10.1: requirement openssl/1.1.1l overridden by ios/1.0.0 to openssl/1.1.1k 
ERROR: darwin-toolchain/1.3.0@ezored/stable: Invalid configuration: macOS: Only supported archs: [x86, x86_64]
COMMAND: conan install /Users/ahmed/Projects/ezored/files/targets/ios/conan/recipe/conanfile.py -pr:b default -pr:h ezored_ios_profile -s:h arch=armv7 -s:h build_type=Debug -s:h os.version=9.0 -s:b os.version=None -o ezored_arch=armv7 -o ezored_name=ezored -o ezored_version=1.0.0 -o ezored_group=ios -o darwin-toolchain:enable_bitcode=True -o darwin-toolchain:enable_arc=None -o darwin-toolchain:enable_visibility=None --build=missing --update
WORKING DIR: /Users/ahmed/Projects/ezored/build/ios/Debug/ios/armv7/conan
[ERROR] Command execution has failed
```

**Comment by paulocoutinhox** [comment]
Hi,

Can you try latest master version?

Because darwin-toolchain used is other version:
https://github.com/ezored/ezored/blob/main/files/targets/ios/conan/profile/ezored_ios_profile

But i think that main problem is darwin-toolchain on new m1 CPU:
https://github.com/ezored/conan-darwin-toolchain/blob/stable/1.4.0/conanfile.py#L49

I added a new version (1.5.0) with m1 support. 

Can you test the new version (1.5.0) and post here if you still with problems?

Thanks.

**Comment by ahmedkamalio** [comment]
Hi @paulo-coutinho , The 1.5.0 works well, thank you!
